services:
  gititdone_app:
    container_name: gititdone_app
    image: javeexd/gamestore-app:latest
    build: .
    ports:
      - 8080:8080
    networks:
      - gititdone_network
    environment:
      - DB_HOST=gititdone_db
      - DB_PORT=5432
      - DB_NAME=gamestore
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - gititdone_db
  datadog-agent:
    image: datadog/agent:latest
    environment:
      - DD_API_KEY=72cab1ec49a23ca6d5abc96eb9e35067 # Reemplaza con tu API key de Datadog
      - DD_SITE=datadoghq.com # Cambia esto si usas una región diferente
      - DD_DOGSTATSD_PORT=8125
      - DD_LOGS_ENABLED=true
      - DD_LOGS_CONFIG_LOGS_ENABLED=true
    ports:
      - "8125:8125/udp" # Puerto para DogStatsD
      - "10514:10514/tcp" # Puerto para logs
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Permite al agente leer el estado de Docker
  gititdone_db:
    container_name: gititdone_db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gamestore
    volumes:
      - gititdone_gititdone_db-data:/var/lib/postgresql/data
    networks:
      - gititdone_network
  test:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    environment:
      - DB_HOST=gititdone_db
      - DB_PORT=5432
      - DB_NAME=gamestore
      - DB_USER=postgres
      - DB_PASSWORD=postgres
    depends_on:
      - gititdone_db
    command: mvn test
    networks:
      - gititdone_network
volumes:
  gititdone_gititdone_db-data:
networks:
  gititdone_network:
