name: Java CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Application to Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
         ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy docker-compose.yml to server
        run: |
          scp -o StrictHostKeyChecking=no docker-compose.yml ubuntu@$3.18.128.13:/home/ubuntu/gamestore/

      - name: Remove old container and images
        run: |
          ssh ubuntu@$3.18.128.13 "cd /home/ubuntu/gamestore/ && docker-compose down gamestore-app && docker rmi javeexd/gamestore-app"

      - name: Pull Docker images
        run: |
          ssh ubuntu@$3.18.128.13 "cd /home/ubuntu/gamestore/ && docker-compose pull javeexd/gamestore-app"

      - name: Run Docker Compose
        run: |
          ssh ubuntu@$3.18.128.13 "cd /home/ubuntu/gamestore/ && docker-compose up -d javeexd/gamestore-app"
#       name: Deploy to Render
#        if: github.ref == 'refs/heads/master'
#        env:
#          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
#        run: |
#          curl -X POST $deploy_url
