name: Java CD

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Application to Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Debug private key
        run: echo "${{ vars.SSH_PRIVATE_KEY }}"

      - name: Set up SSH agent
        run: |
          eval "$(ssh-agent -s)"
          echo "${{ vars.SSH_PRIVATE_KEY }}" > /tmp/private_key
          chmod 600 /tmp/private_key
          ssh-add /tmp/private_key
      #- name: Add known hosts
      #  run: ssh-keyscan 3.18.128.13 >> ~/.ssh/known_host

      - name: Copy docker-compose.yml to server
        run: | 
          scp -o StrictHostKeyChecking=no docker-compose.yml ubuntu@3.18.128.13:/home/ubuntu/gamestore/

      - name: Remove old container and images
        run: |
          ssh ubuntu@3.18.128.13 "cd /home/ubuntu/gamestore/ && docker-compose down gamestore-app && docker rmi javeexd/gamestore-app"

      - name: Pull Docker images
        run: |
          ssh ubuntu@3.18.128.13 "cd /home/ubuntu/gamestore/ && docker-compose pull javeexd/gamestore-app"

      - name: Run Docker Compose
        run: |
          ssh ubuntu@3.18.128.13 "cd /home/ubuntu/gamestore/ && docker-compose up -d javeexd/gamestore-app"
#       name: Deploy to Render
#        if: github.ref == 'refs/heads/master'
#        env:
#          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
#        run: |
#          curl -X POST $deploy_url