name: Java CD


on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy Application to Server
    runs-on: ubuntu-latest
    needs: build 

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin

      - name: Pull Docker Image from Docker Hub
        run: docker pull javeexd/gamestore-app:latest

      - name: Stop Existing Container (if any)
        run: |
          docker ps -q --filter "name=gamestore-container" | grep -q . && docker stop gamestore-container || echo "No container to stop"

      - name: Remove Existing Container (if any)
        run: |
          docker ps -a -q --filter "name=gamestore-container" | grep -q . && docker rm gamestore-container || echo "No container to remove"

      - name: Run New Container
        run: |
          docker run -d --name gamestore-container -p 80:80 javeexd/gamestore-app:latest
